export const todosConstants = {
  GET_TODOS_IN_PROCESS: 'GET_TODOS_IN_PROCESS',
  GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
  GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',

  CREATE_TODO_IN_PROCESS: 'CREATE_TODO_IN_PROCESS',
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_FAILURE: 'CREATE_TODO_FAILURE',

  REMOVE_TODO_IN_PROCESS: 'REMOVE_TODO_IN_PROCESS',
  REMOVE_TODO_SUCCESS: 'REMOVE_TODO_SUCCESS',
  REMOVE_TODO_FAILURE: 'REMOVE_TODO_FAILURE',

  SWITCH_TODO_STATUS_IN_PROCESS: 'SWITCH_TODO_STATUS_IN_PROCESS',
  SWITCH_TODO_STATUS_SUCCESS: 'SWITCH_TODO_STATUS_SUCCESS',
  SWITCH_TODO_STATUS_FAILURE: 'SWITCH_TODO_STATUS_FAILURE',

  EDIT_TODO_IN_PROCESS: 'EDIT_TODO_IN_PROCESS',
  EDIT_TODO_SUCCESS: 'EDIT_TODO_SUCCESS',
  EDIT_TODO_FAILURE: 'EDIT_TODO_FAILURE'
};
